name: "Test"
on:
  pull_request:
jobs:
  test-nix:
    name: 'Nix'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: 'Install Nix'
        uses: cachix/install-nix-action@v12

      - name: 'Install Cachix'
        uses: cachix/cachix-action@v8
        with:
          name: runtimeverification
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: 'Build K Framework'
        run: nix-build -A k -A llvm-backend -A haskell-backend

      - name: 'Check development environment'
        run: nix-shell --run "echo OK"

      - name: 'Run integration tests'
        run: nix-build test.nix

  # Update README.md if this job changes.
  test-nix-install:
    name: 'Nix: Install'
    needs: test-nix
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test end-to-end installation instructions
        run: |
          bash <(curl -L https://nixos.org/nix/install)
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use runtimeverification
          nix-env -f https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz \
            -i -A k -A haskell-backend -A llvm-backend
